name: hmt_smlm
channels:
  - conda-forge

dependencies:
  - python=3.11

  # core science
  - numpy
  - scipy
  - numba
  - scikit-learn
  - hdbscan
  - lmfit

  # visualization
  - matplotlib
  - napari
  - magicgui

  # SMLM analysis
  - locan

  # data
  - pandas
  - dask
  - imageio
  - imagecodecs

  # optional geo stack
  - geopandas
  - folium
  - esda
  - mapclassify

  # notebooks
  - jupyterlab
  - ipykernel
  - ipywidgets
  - nbstripout