function []=gen_ovito_fin2(eux,euy,euz,hetx,hety,hetz,f1x,f1y,f1z,outputFileName)
% Parameters for the simulation
numParticles = length([eux;hetx;f1x]); % Number of particles

% Generate random particle positions within the box
%particlePositions = bsxfun(@times, rand(numParticles, 3), boxSize);
particlePositions=[eux,euy,euz;hetx,hety,hetz;f1x,f1y,f1z];
% Generate particle types (randomly assign He or Li)
part1=2*ones(length(eux),1);
part2=ones(length(hetx),1);
part3=3*ones(length(f1x),1);
particleTypes = [part1;part2;part3]; % 1 for He, 2 for Li
particleTypeNames = ["He", "Li","Be"];
Transparency=[0.8*ones(length(eux),1);0.8*ones(length(hetx),1);0*ones(length(f1x),1)];
% File name for the OVITO output

% Open the file for writing
fileID = fopen(outputFileName, 'w');

% Write the header information for the XYZ file
fprintf(fileID, '%d\n', numParticles);
fprintf(fileID, 'Generated by MATLAB for OVITO\n');

% Write the particle data to the file
for i = 1:numParticles
    fprintf(fileID, '%s %f %f %f %f\n', ...
        particleTypeNames(particleTypes(i)), ...
        particlePositions(i, 1), particlePositions(i, 2), particlePositions(i, 3),Transparency(i));
        
end

% Close the file
fclose(fileID);

disp(['Particle data with types written to ', outputFileName]);